### ISSUE TITLE
[ERROR] Exception occurred while handling uri: 

### ISSUE THREAD

**Issue by exbane** [PureStorage-OpenConnect/pure-fa-openmetrics-exporter#4]
Hello - i've been able to get the docker image up and running on a RHEL8 VM.. when i configure the promethues yml file for the FA i start getting these messages in the error log of the collector.. i can see the user account loging into the array with the api token but no data is being handled.. Thoughts? 

i'm using the 0.1.0 version and i've tried 0.2.0-dev.. also whenever i try to use the --workers command i get errors too.. only seems to start the container successfully when its one worker.. 

[2022-09-07 20:54:06 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://boop:9491/metrics?endpoint=10.32.33.34'
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    FutureStatic,
  File "/app/pure_fa_exporter.py", line 51, in decorated_function
    response = await f(request, *args, **kwargs)
  File "/app/pure_fa_exporter.py", line 113, in flasharray_handler
    resp = generate_latest(registry)
  File "/app/.local/lib/python3.10/site-packages/prometheus_client/exposition.py", line 197, in generate_latest
    for metric in registry.collect():
  File "/app/.local/lib/python3.10/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/app/.local/lib/python3.10/site-packages/pure_fa_openmetrics_exporter/flasharray_collector/collector.py", line 34, in collect
    yield from ArrayInfoMetrics(self.fa).get_metrics()
  File "/app/.local/lib/python3.10/site-packages/pure_fa_openmetrics_exporter/flasharray_collector/flasharray_metrics/array_info_metrics.py", line 8, in __init__
    self.array = fa_client.arrays()[0]
  File "/app/.local/lib/python3.10/site-packages/pure_fa_openmetrics_exporter/flasharray_client/client.py", line 66, in arrays
    return list(self._arrays.values())
AttributeError: 'NoneType' object has no attribute 'values'

**Comment by exbane** [comment]
bump

**Comment by sdodsley** [comment]
@exbane we are refactoring this code to run under GoLang.  This will be much moe robust and handle errors cleanly.
We will not be doing any further development work on the Python version.
The Go version will be available shortly.

**Comment by genegr** [comment]
The new Go version is available and should fix among the other issues also this one. Please give it a try to see this is actually fixed.
